tap "libsql/sqld"
tap "supabase/tap"
tap "tursodatabase/tap"
brew "biome"
brew "fzf"
brew "gh"
brew "lefthook"
brew "nvm"
brew "stow"
brew "supabase", link: false
brew "zsh"
brew "tursodatabase/tap/turso"
cask "unnaturalscrollwheels"
